import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Sidebar configuration for nauth-toolkit documentation
 *
 * Docs sidebar: Manual structure for guides, concepts, and quick start
 * API sidebar: Hybrid — manual top-level structure with autogenerated leaf categories
 * Frontend SDK sidebar: Manually curated for developer journeys
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'doc',
      id: 'intro',
      customProps: { icon: 'fa-light fa-house' },
    },
    {
      type: 'doc',
      id: 'concepts/how-it-works',
      customProps: { icon: 'fa-light fa-circle-nodes' },
    },

    {
      type: 'category',
      label: 'Quick Start',
      collapsible: true,
      collapsed: false,
      customProps: { icon: 'fa-light fa-rocket' },
      items: [
        {
          type: 'category',
          label: 'Backend',
          collapsible: true,
          collapsed: false,
          customProps: { icon: 'fa-light fa-server' },
          items: [
            { type: 'doc', id: 'quick-start/nestjs', customProps: { icon: 'fa-kit fa-nestjs-light' } },
            { type: 'doc', id: 'quick-start/express', customProps: { icon: 'fa-kit fa-express' } },
            { type: 'doc', id: 'quick-start/fastify', customProps: { icon: 'fa-light fa-bolt' } },
          ],
        },
        {
          type: 'category',
          label: 'Frontend',
          collapsible: true,
          collapsed: false,
          customProps: { icon: 'fa-light fa-display' },
          items: [
            { type: 'doc', id: 'quick-start/angular', customProps: { icon: 'fa-brands fa-angular' } },
            { type: 'doc', id: 'quick-start/react', customProps: { icon: 'fa-brands fa-react' } },
          ],
        },
      ],
    },

    {
      type: 'category',
      label: 'Guides',
      collapsible: true,
      collapsed: false,
      customProps: { icon: 'fa-light fa-book-open' },
      items: [
        { type: 'doc', id: 'guides/basic-auth', customProps: { icon: 'fa-light fa-right-to-bracket' } },
        {
          type: 'category',
          label: 'MFA',
          collapsible: true,
          collapsed: true,
          customProps: { icon: 'fa-light fa-shield-halved' },
          items: [
            { type: 'doc', id: 'guides/mfa/how-mfa-works', customProps: { icon: 'fa-light fa-circle-info' } },
            { type: 'doc', id: 'guides/mfa/email', customProps: { icon: 'fa-light fa-envelope' } },
            { type: 'doc', id: 'guides/mfa/sms', customProps: { icon: 'fa-light fa-message' } },
            { type: 'doc', id: 'guides/mfa/totp', customProps: { icon: 'fa-light fa-clock' } },
            { type: 'doc', id: 'guides/mfa/passkey', customProps: { icon: 'fa-light fa-fingerprint' } },
          ],
        },
        {
          type: 'category',
          label: 'Social Login',
          collapsible: true,
          collapsed: true,
          customProps: { icon: 'fa-light fa-share-nodes' },
          items: [
            {
              type: 'doc',
              id: 'guides/social/how-social-login-works',
              customProps: { icon: 'fa-light fa-circle-info' },
            },
            { type: 'doc', id: 'guides/social/google', customProps: { icon: 'fa-brands fa-google' } },
            { type: 'doc', id: 'guides/social/apple', customProps: { icon: 'fa-brands fa-apple' } },
            { type: 'doc', id: 'guides/social/facebook', customProps: { icon: 'fa-brands fa-facebook-f' } },
          ],
        },
        { type: 'doc', id: 'guides/admin-operations', customProps: { icon: 'fa-light fa-user-gear' } },
        { type: 'doc', id: 'guides/email-sms-providers', customProps: { icon: 'fa-light fa-paper-plane' } },
        { type: 'doc', id: 'guides/email-templates', customProps: { icon: 'fa-light fa-envelope-open-text' } },
        { type: 'doc', id: 'guides/sms-templates', customProps: { icon: 'fa-light fa-comment-sms' } },
        { type: 'doc', id: 'guides/lifecycle-hooks', customProps: { icon: 'fa-light fa-webhook' } },
        { type: 'doc', id: 'guides/geolocation', customProps: { icon: 'fa-light fa-location-dot' } },
        { type: 'doc', id: 'guides/audit-logs', customProps: { icon: 'fa-light fa-clipboard-list' } },
        { type: 'doc', id: 'guides/rate-limiting', customProps: { icon: 'fa-light fa-gauge-high' } },
        { type: 'doc', id: 'guides/recaptcha', customProps: { icon: 'fa-light fa-robot' } },
        { type: 'doc', id: 'guides/openapi-dto-schemas', customProps: { icon: 'fa-light fa-brackets-curly' } },
        { type: 'doc', id: 'guides/routes', customProps: { icon: 'fa-light fa-route' } },
      ],
    },

    {
      type: 'category',
      label: 'Concepts',
      collapsible: true,
      collapsed: true,
      customProps: { icon: 'fa-light fa-lightbulb' },
      items: [
        { type: 'doc', id: 'concepts/configuration', customProps: { icon: 'fa-light fa-sliders' } },
        { type: 'doc', id: 'concepts/challenge-system', customProps: { icon: 'fa-light fa-arrows-rotate' } },
        { type: 'doc', id: 'concepts/token-management', customProps: { icon: 'fa-light fa-key' } },
        { type: 'doc', id: 'concepts/storage', customProps: { icon: 'fa-light fa-database' } },
        { type: 'doc', id: 'concepts/error-handling', customProps: { icon: 'fa-light fa-triangle-exclamation' } },
        { type: 'doc', id: 'concepts/notifications', customProps: { icon: 'fa-light fa-bell' } },
        { type: 'doc', id: 'concepts/lifecycle-hooks', customProps: { icon: 'fa-light fa-webhook' } },
        { type: 'doc', id: 'concepts/audit-logs', customProps: { icon: 'fa-light fa-clipboard-list' } },
      ],
    },
  ],

  // API Reference sidebar - hybrid: manual structure + autogenerated leaf categories
  apiSidebar: [
    {
      type: 'doc',
      id: 'api/overview',
      label: 'Overview',
      customProps: { icon: 'fa-light fa-map' },
    },

    // ─── Core Package ──────────────────────────────────────────────────
    {
      type: 'category',
      label: 'Core',
      collapsed: false,
      link: null,
      customProps: { icon: 'fa-light fa-cube' },
      items: [
        {
          type: 'category',
          label: 'Services',
          collapsed: true,
          link: null,
          items: [{ type: 'autogenerated', dirName: 'api/core/services' }],
        },
        {
          type: 'category',
          label: 'DTOs',
          collapsed: true,
          link: null,
          items: [{ type: 'autogenerated', dirName: 'api/core/dto' }],
        },
        {
          type: 'category',
          label: 'Hooks',
          collapsed: true,
          link: null,
          items: [{ type: 'autogenerated', dirName: 'api/core/hooks' }],
        },
        {
          type: 'category',
          label: 'Enums',
          collapsed: true,
          link: null,
          items: [{ type: 'autogenerated', dirName: 'api/core/enums' }],
        },
        {
          type: 'category',
          label: 'Interfaces',
          collapsed: true,
          link: null,
          items: [{ type: 'autogenerated', dirName: 'api/core/interfaces' }],
        },
        {
          type: 'category',
          label: 'Exceptions',
          collapsed: true,
          link: null,
          items: [{ type: 'autogenerated', dirName: 'api/core/exceptions' }],
        },
      ],
    },

    // ─── NestJS Adapter ────────────────────────────────────────────────
    {
      type: 'category',
      label: 'NestJS',
      collapsed: true,
      link: null,
      customProps: { icon: 'fa-kit fa-nestjs-light' },
      items: [
        { type: 'doc', id: 'api/nestjs/overview', label: 'Overview' },
        {
          type: 'category',
          label: 'Guards',
          collapsed: true,
          link: null,
          items: [{ type: 'autogenerated', dirName: 'api/nestjs/guards' }],
        },
        {
          type: 'category',
          label: 'Decorators',
          collapsed: true,
          link: null,
          items: [
            { type: 'doc', id: 'api/nestjs/decorators/client-info' },
            { type: 'doc', id: 'api/nestjs/decorators/current-user' },
            { type: 'doc', id: 'api/nestjs/decorators/public' },
            { type: 'doc', id: 'api/nestjs/decorators/token-delivery' },
            { type: 'doc', id: 'api/nestjs/decorators/require-recaptcha' },
          ],
        },
        {
          type: 'category',
          label: 'Lifecycle Hooks',
          collapsed: true,
          link: null,
          items: [
            { type: 'doc', id: 'api/nestjs/decorators/nauth-hooks-module' },
            { type: 'doc', id: 'api/nestjs/decorators/account-locked-hook' },
            { type: 'doc', id: 'api/nestjs/decorators/account-status-changed-hook' },
            { type: 'doc', id: 'api/nestjs/decorators/adaptive-mfa-risk-detected-hook' },
            { type: 'doc', id: 'api/nestjs/decorators/email-changed-hook' },
            { type: 'doc', id: 'api/nestjs/decorators/mfa-device-removed-hook' },
            { type: 'doc', id: 'api/nestjs/decorators/mfa-first-enabled-hook' },
            { type: 'doc', id: 'api/nestjs/decorators/password-changed-hook' },
            { type: 'doc', id: 'api/nestjs/decorators/post-signup-hook' },
            { type: 'doc', id: 'api/nestjs/decorators/pre-signup-hook' },
            { type: 'doc', id: 'api/nestjs/decorators/sessions-revoked-hook' },
            { type: 'doc', id: 'api/nestjs/decorators/user-profile-updated-hook' },
          ],
        },
        {
          type: 'category',
          label: 'Pipes',
          collapsed: true,
          link: null,
          items: [{ type: 'autogenerated', dirName: 'api/nestjs/pipes' }],
        },
        {
          type: 'category',
          label: 'Interceptors',
          collapsed: true,
          link: null,
          items: [{ type: 'autogenerated', dirName: 'api/nestjs/interceptors' }],
        },
        {
          type: 'category',
          label: 'Filters',
          collapsed: true,
          link: null,
          items: [{ type: 'autogenerated', dirName: 'api/nestjs/filters' }],
        },
        {
          type: 'category',
          label: 'Providers',
          collapsed: true,
          link: null,
          items: [{ type: 'autogenerated', dirName: 'api/nestjs/providers' }],
        },
      ],
    },

    // ─── Express Adapter ───────────────────────────────────────────────
    {
      type: 'category',
      label: 'Express',
      collapsed: true,
      link: null,
      customProps: { icon: 'fa-kit fa-express' },
      items: [
        { type: 'doc', id: 'api/express/overview', label: 'Overview' },
        {
          type: 'category',
          label: 'Middleware',
          collapsed: true,
          link: null,
          items: [{ type: 'autogenerated', dirName: 'api/express/middleware' }],
        },
        {
          type: 'category',
          label: 'Helpers',
          collapsed: true,
          link: null,
          items: [{ type: 'autogenerated', dirName: 'api/express/helpers' }],
        },
      ],
    },

    // ─── Fastify Adapter ───────────────────────────────────────────────
    {
      type: 'category',
      label: 'Fastify',
      collapsed: true,
      link: null,
      customProps: { icon: 'fa-light fa-bolt' },
      items: [
        { type: 'doc', id: 'api/fastify/overview', label: 'Overview' },
        {
          type: 'category',
          label: 'Hooks',
          collapsed: true,
          link: null,
          items: [{ type: 'autogenerated', dirName: 'api/fastify/hooks' }],
        },
        {
          type: 'category',
          label: 'Helpers',
          collapsed: true,
          link: null,
          items: [{ type: 'autogenerated', dirName: 'api/fastify/helpers' }],
        },
      ],
    },

    // ─── Providers (all optional packages) ─────────────────────────────
    {
      type: 'category',
      label: 'Providers',
      collapsed: true,
      link: null,
      customProps: { icon: 'fa-light fa-puzzle-piece' },
      items: [
        {
          type: 'category',
          label: 'MFA',
          collapsed: true,
          link: null,
          items: [{ type: 'autogenerated', dirName: 'api/mfa' }],
        },
        {
          type: 'category',
          label: 'Social Auth',
          collapsed: true,
          link: null,
          items: [{ type: 'autogenerated', dirName: 'api/social' }],
        },
        {
          type: 'category',
          label: 'Email',
          collapsed: true,
          link: null,
          items: [{ type: 'autogenerated', dirName: 'api/email' }],
        },
        {
          type: 'category',
          label: 'SMS',
          collapsed: true,
          link: null,
          items: [{ type: 'autogenerated', dirName: 'api/sms' }],
        },
        {
          type: 'category',
          label: 'Database',
          collapsed: true,
          link: null,
          items: [{ type: 'autogenerated', dirName: 'api/database' }],
        },
        {
          type: 'category',
          label: 'Session Storage',
          collapsed: true,
          link: null,
          items: [{ type: 'autogenerated', dirName: 'api/storage' }],
        },
        {
          type: 'category',
          label: 'reCAPTCHA',
          collapsed: true,
          link: null,
          items: [{ type: 'autogenerated', dirName: 'api/recaptcha' }],
        },
      ],
    },
  ],

  // Frontend SDK sidebar - manually curated for clear developer journeys
  frontendSdkSidebar: [
    {
      type: 'doc',
      id: 'frontend-sdk/overview',
      label: 'Overview',
      customProps: { icon: 'fa-light fa-display-code' },
    },
    {
      type: 'doc',
      id: 'frontend-sdk/guides/getting-started',
      label: 'Getting Started',
      customProps: { icon: 'fa-light fa-play' },
    },

    // ─── Framework Guides ────────────────────────────────────────────
    {
      type: 'category',
      label: 'Angular',
      collapsible: true,
      collapsed: false,
      customProps: { icon: 'fa-brands fa-angular' },
      items: [
        { type: 'doc', id: 'frontend-sdk/angular/standalone-setup', label: 'Standalone Setup', customProps: { icon: 'fa-light fa-bolt' } },
        { type: 'doc', id: 'frontend-sdk/angular/ngmodule-setup', label: 'NgModule Setup', customProps: { icon: 'fa-light fa-cube' } },
        { type: 'doc', id: 'frontend-sdk/angular/auth-service', label: 'AuthService', customProps: { icon: 'fa-light fa-gear' } },
        { type: 'doc', id: 'frontend-sdk/angular/guards', label: 'Guards', customProps: { icon: 'fa-light fa-shield' } },
        { type: 'doc', id: 'frontend-sdk/angular/interceptor', label: 'HTTP Interceptor', customProps: { icon: 'fa-light fa-arrows-rotate' } },
        { type: 'doc', id: 'frontend-sdk/angular/oauth-callback-guard', label: 'OAuth Callback', customProps: { icon: 'fa-light fa-arrow-right-to-bracket' } },
      ],
    },
    {
      type: 'category',
      label: 'React',
      collapsible: true,
      collapsed: true,
      customProps: { icon: 'fa-brands fa-react' },
      items: [
        { type: 'doc', id: 'frontend-sdk/react/setup', label: 'Setup & Context', customProps: { icon: 'fa-light fa-bolt' } },
        { type: 'doc', id: 'frontend-sdk/react/protected-routes', label: 'Protected Routes', customProps: { icon: 'fa-light fa-shield' } },
        { type: 'doc', id: 'frontend-sdk/react/oauth-callback', label: 'OAuth Callback', customProps: { icon: 'fa-light fa-arrow-right-to-bracket' } },
      ],
    },
    {
      type: 'category',
      label: 'Mobile / Native',
      collapsible: true,
      collapsed: true,
      customProps: { icon: 'fa-light fa-mobile' },
      items: [
        {
          type: 'doc',
          id: 'frontend-sdk/mobile/capacitor-setup',
          label: 'Capacitor Setup',
          customProps: { icon: 'fa-light fa-bolt' },
        },
        {
          type: 'doc',
          id: 'frontend-sdk/mobile/native-social',
          label: 'Native Social Login',
          customProps: { icon: 'fa-light fa-share-nodes' },
        },
      ],
    },

    // ─── Feature Guides ──────────────────────────────────────────────
    {
      type: 'category',
      label: 'Feature Guides',
      collapsible: true,
      collapsed: true,
      customProps: { icon: 'fa-light fa-book-open' },
      items: [
        { type: 'doc', id: 'frontend-sdk/guides/challenge-handling', label: 'Challenge Handling', customProps: { icon: 'fa-light fa-arrows-rotate' } },
        { type: 'doc', id: 'frontend-sdk/guides/mfa-setup', label: 'MFA Setup', customProps: { icon: 'fa-light fa-shield-halved' } },
        { type: 'doc', id: 'frontend-sdk/guides/social-auth', label: 'Social Authentication', customProps: { icon: 'fa-light fa-share-nodes' } },
        { type: 'doc', id: 'frontend-sdk/guides/authentication-events', label: 'Authentication Events', customProps: { icon: 'fa-light fa-bell' } },
        {
          type: 'doc',
          id: 'frontend-sdk/guides/error-handling',
          label: 'Error Handling',
          customProps: { icon: 'fa-light fa-triangle-exclamation' },
        },
        {
          type: 'doc',
          id: 'frontend-sdk/api/admin-operations',
          label: 'Admin Operations',
          customProps: { icon: 'fa-light fa-user-gear' },
        },
      ],
    },

    // ─── Concepts ────────────────────────────────────────────────────
    {
      type: 'category',
      label: 'Concepts',
      collapsible: true,
      collapsed: true,
      customProps: { icon: 'fa-light fa-lightbulb' },
      items: [
        { type: 'doc', id: 'frontend-sdk/concepts/configuration', label: 'Configuration', customProps: { icon: 'fa-light fa-sliders' } },
        { type: 'doc', id: 'frontend-sdk/concepts/token-management', label: 'Token Management', customProps: { icon: 'fa-light fa-key' } },
      ],
    },

    // ─── API Reference ───────────────────────────────────────────────
    {
      type: 'category',
      label: 'API Reference',
      collapsible: true,
      collapsed: true,
      customProps: { icon: 'fa-light fa-brackets-curly' },
      items: [
        { type: 'doc', id: 'frontend-sdk/api/overview', label: 'Overview' },
        { type: 'doc', id: 'frontend-sdk/api/nauth-client', label: 'NAuthClient' },
        { type: 'doc', id: 'frontend-sdk/api/nauth-client-config', label: 'NAuthClientConfig' },
        { type: 'doc', id: 'frontend-sdk/api/nauth-client-error', label: 'NAuthClientError' },
        { type: 'doc', id: 'frontend-sdk/api/utilities/challenge-helpers', label: 'Challenge Helpers' },
        {
          type: 'category',
          label: 'Types',
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'frontend-sdk/api/types',
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
