import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Sidebar configuration for nauth-toolkit documentation
 *
 * Docs sidebar: Manual structure excluding API folder
 * API sidebar: Autogenerated from api folder only
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar - manually structured to exclude api folder
  docsSidebar: [
    'intro',
    'quick-start',
    {
      type: 'category',
      label: 'Concepts',
      collapsible: true,
      collapsed: false,
      items: [
        'concepts/architecture',
        'concepts/challenge-system',
        'concepts/storage',
        'concepts/configuration',
        'concepts/error-handling',
      ],
    },
    {
      type: 'category',
      label: 'Features',
      collapsible: true,
      collapsed: false,
      items: [
        'features/social-login',
        'features/mfa',
        'features/email-templates',
        'features/token-delivery',
        'features/geolocation',
        'features/testing',
        'features/deployment',
      ],
    },
  ],

  // Guides sidebar (empty for now - add as content is created)
  guidesSidebar: [
    // Coming soon
  ],

  // API Reference sidebar - autogenerated from api folder only
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api', // Generate from the api folder
    },
  ],
};

export default sidebars;
