/**
 * Standardized error codes mirroring backend AuthErrorCode.
 */
export enum NAuthErrorCode {
  // Authentication Errors
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_INACTIVE = 'AUTH_ACCOUNT_INACTIVE',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_BEARER_NOT_ALLOWED = 'AUTH_BEARER_NOT_ALLOWED',
  AUTH_COOKIES_NOT_ALLOWED = 'AUTH_COOKIES_NOT_ALLOWED',
  AUTH_CSRF_TOKEN_INVALID = 'AUTH_CSRF_TOKEN_INVALID',
  AUTH_CSRF_TOKEN_MISSING = 'AUTH_CSRF_TOKEN_MISSING',
  AUTH_TOKEN_REUSE_DETECTED = 'AUTH_TOKEN_REUSE_DETECTED',
  AUTH_SESSION_NOT_FOUND = 'AUTH_SESSION_NOT_FOUND',
  AUTH_SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',

  // Signup Errors
  SIGNUP_DISABLED = 'SIGNUP_DISABLED',
  SIGNUP_EMAIL_EXISTS = 'SIGNUP_EMAIL_EXISTS',
  SIGNUP_USERNAME_EXISTS = 'SIGNUP_USERNAME_EXISTS',
  SIGNUP_PHONE_EXISTS = 'SIGNUP_PHONE_EXISTS',
  SIGNUP_WEAK_PASSWORD = 'SIGNUP_WEAK_PASSWORD',
  SIGNUP_PHONE_REQUIRED = 'SIGNUP_PHONE_REQUIRED',
  SIGNUP_NOT_ALLOWED = 'SIGNUP_NOT_ALLOWED',

  // Verification Errors
  VERIFY_CODE_INVALID = 'VERIFY_CODE_INVALID',
  VERIFY_CODE_EXPIRED = 'VERIFY_CODE_EXPIRED',
  VERIFY_TOO_MANY_ATTEMPTS = 'VERIFY_TOO_MANY_ATTEMPTS',
  VERIFY_ALREADY_VERIFIED = 'VERIFY_ALREADY_VERIFIED',

  // MFA Errors
  MFA_SETUP_REQUIRED = 'MFA_SETUP_REQUIRED',

  // Rate Limit Errors
  RATE_LIMIT_SMS = 'RATE_LIMIT_SMS',
  RATE_LIMIT_EMAIL = 'RATE_LIMIT_EMAIL',
  RATE_LIMIT_LOGIN = 'RATE_LIMIT_LOGIN',
  RATE_LIMIT_RESEND = 'RATE_LIMIT_RESEND',

  // Social Auth Errors
  SOCIAL_TOKEN_INVALID = 'SOCIAL_TOKEN_INVALID',
  SOCIAL_ACCOUNT_LINKED = 'SOCIAL_ACCOUNT_LINKED',
  SOCIAL_CONFIG_MISSING = 'SOCIAL_CONFIG_MISSING',
  SOCIAL_EMAIL_REQUIRED = 'SOCIAL_EMAIL_REQUIRED',
  SOCIAL_ACCOUNT_NOT_FOUND = 'SOCIAL_ACCOUNT_NOT_FOUND',

  // Challenge Errors
  CHALLENGE_EXPIRED = 'CHALLENGE_EXPIRED',
  CHALLENGE_INVALID = 'CHALLENGE_INVALID',
  CHALLENGE_TYPE_MISMATCH = 'CHALLENGE_TYPE_MISMATCH',
  CHALLENGE_MAX_ATTEMPTS = 'CHALLENGE_MAX_ATTEMPTS',
  CHALLENGE_ALREADY_COMPLETED = 'CHALLENGE_ALREADY_COMPLETED',

  // Validation Errors
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  VALIDATION_INVALID_PHONE = 'VALIDATION_INVALID_PHONE',
  VALIDATION_INVALID_EMAIL = 'VALIDATION_INVALID_EMAIL',
  VALIDATION_INVALID_PASSWORD = 'VALIDATION_INVALID_PASSWORD',

  // Password Errors
  PASSWORD_INCORRECT = 'PASSWORD_INCORRECT',
  PASSWORD_REUSED = 'PASSWORD_REUSED',
  PASSWORD_CHANGE_NOT_ALLOWED = 'PASSWORD_CHANGE_NOT_ALLOWED',
  WEAK_PASSWORD = 'SIGNUP_WEAK_PASSWORD',
  PASSWORD_RESET_CODE_INVALID = 'PASSWORD_RESET_CODE_INVALID',
  PASSWORD_RESET_CODE_EXPIRED = 'PASSWORD_RESET_CODE_EXPIRED',
  PASSWORD_RESET_MAX_ATTEMPTS = 'PASSWORD_RESET_MAX_ATTEMPTS',
  RATE_LIMIT_PASSWORD_RESET = 'RATE_LIMIT_PASSWORD_RESET',

  // Adaptive MFA
  SIGNIN_BLOCKED_HIGH_RISK = 'SIGNIN_BLOCKED_HIGH_RISK',

  // Identity Provider (OpenID Connect) Errors
  OIDC_INTERACTION_NOT_FOUND = 'OIDC_INTERACTION_NOT_FOUND',
  OIDC_LOGIN_REQUIRED = 'OIDC_LOGIN_REQUIRED',
  OIDC_ACCESS_DENIED = 'OIDC_ACCESS_DENIED',

  // General Errors
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  FORBIDDEN = 'FORBIDDEN',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
}

/**
 * Structured client error.
 */
export interface NAuthError {
  code: NAuthErrorCode;
  message: string;
  details?: Record<string, unknown>;
  timestamp?: string;
  statusCode?: number;
}
