/**
 * Google reCAPTCHA provider interface
 *
 * Supports v2, v3, and Enterprise versions of Google reCAPTCHA.
 * Implementations should handle token verification with Google's API.
 *
 * @example
 * ```typescript
 * const provider = new RecaptchaV3Provider({ secretKey: 'your-secret' });
 * const result = await provider.verify(token, clientIp, 'login');
 * if (result.success) {
 *   console.log('Valid token');
 * }
 * ```
 */
export interface RecaptchaProvider {
  /**
   * Verify reCAPTCHA token with Google's API
   *
   * @param token - Token from client (generated by Google reCAPTCHA)
   * @param remoteIp - Client IP address (optional but recommended for security)
   * @param action - Action name for v3/Enterprise (e.g., 'login', 'signup')
   * @returns Verification result with score (v3/Enterprise) or success (v2)
   *
   * @example
   * ```typescript
   * const result = await provider.verify(
   *   'token-from-client',
   *   '192.168.1.1',
   *   'login'
   * );
   * ```
   */
  verify(token: string, remoteIp?: string, action?: string): Promise<RecaptchaVerificationResult>;

  /**
   * Validate provider configuration at startup
   *
   * Makes a lightweight probe request to Google's API to verify that
   * credentials are correct and the API is reachable. Uses a known-bad
   * token so no real assessment is created.
   *
   * This method is optional. If not implemented, startup validation
   * is skipped for this provider.
   *
   * @returns Validation result with actionable error messages
   */
  validateConfig?(): Promise<RecaptchaValidationResult>;
}

/**
 * Result of startup configuration validation
 *
 * Returned by `validateConfig()` to indicate whether the provider's
 * credentials and API connectivity are correctly configured.
 */
export interface RecaptchaValidationResult {
  /** Whether the configuration is valid and the API is reachable */
  valid: boolean;

  /** Human-readable message describing the validation outcome */
  message: string;

  /**
   * Actionable hint for fixing the issue (only present when valid is false)
   *
   * @example 'Enable the reCAPTCHA Enterprise API at https://console.cloud.google.com/apis/library/recaptchaenterprise.googleapis.com'
   */
  hint?: string;

  /** HTTP status code from the probe request (useful for debugging in logs) */
  httpStatus?: number;
}

/**
 * Result of reCAPTCHA token verification
 *
 * Different fields are populated depending on reCAPTCHA version:
 * - v2: success, challengeTs, hostname
 * - v3: success, score, action, hostname
 * - Enterprise: success, score, action, hostname
 */
export interface RecaptchaVerificationResult {
  /**
   * Whether the token is valid
   */
  success: boolean;

  /**
   * Risk score for v3/Enterprise (0.0 - 1.0)
   *
   * - 0.0: Very likely a bot
   * - 1.0: Very likely a human
   * - Not present for v2
   */
  score?: number;

  /**
   * Action name that was verified (v3/Enterprise only)
   */
  action?: string;

  /**
   * Timestamp of the challenge load (v2 only)
   * ISO 8601 format
   */
  challengeTs?: string;

  /**
   * Hostname of the site where the reCAPTCHA was solved
   */
  hostname?: string;

  /**
   * Error codes returned by Google (if any)
   *
   * Common errors:
   * - missing-input-secret: Secret key is missing
   * - invalid-input-secret: Secret key is invalid
   * - missing-input-response: Token is missing
   * - invalid-input-response: Token is invalid or expired
   * - timeout-or-duplicate: Token has been used or expired
   */
  errorCodes?: string[];
}
